# Wandb
wandb:
  entity: 
  project: 
  resume: allow
  mode: run
  name:
  tags:
  id:

# Hydra
hydra:
  run:
    dir: ${log_dir}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}