# Wandb
wandb:
  entity: jc2318
  project: sampling_tests
  resume: allow
  mode: run
  name:
  tags:
  id:

# Hydra
hydra:
  run:
    dir: ${log_dir}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}