name: credit
dim: 25
has_entropy: False

fn:
  _target_: targets.german_credit.GermanCredit
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale:
  step_size:

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale:

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.1, 0.1]  

smc: # Sequential Monte Carlo Sampler
  initial_scale: 0.1

smc_rebuttal:
  initial_scale: 1.
  target_ess: 0.99
  hmc_step_size: [0.05, 0.001]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 0.1
  step_size: 1e-4

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 0.1
  step_size: 1e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 1
  step_size: 1e-3
  max_diffusion: 6.
  
dis: # Time-reversed Diffusion Sampler
  initial_scale: 1.
  step_size: 1e-3

pis: # Path Integral Sampler
  step_size: 1e-4

cmcd: # CMCD
  initial_scale: 0.1
  max_diffusion: 0.1
  step_size: 1e-3

scld:
  initial_scale: 0.1
  max_diffusion: 0.1
  step_size: 1e-3
  annealing_step_size: 1e-2
  n_sub_traj: 128

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  initial_scale:
  step_size:

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  initial_scale:
  step_size:

gsb:  # General Schroedinger Bridge
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 1e-3

all: # Parameters that are shared between all algorithms
  batch_size: 2000 #500
