name: lgcp
dim: 1600
has_entropy: False

fn:
  _target_: targets.lgcp.LogGaussianCoxPines
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: .1
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 1. # No parameter since GMMVI does not scale to that high dimensions

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.01, 0.2]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 1.

smc_rebuttal:
  initial_scale: 1.
  target_ess: 0.99
  hmc_step_size: [0.001, 0.2]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 1.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 0.1
  step_size: 1e-3

dds: # Denoising Diffusion Sampler
  initial_scale: 0.1
  step_size: 1e-4
  max_diffusion: 6.
pis: # Path Integral Sampler
  step_size: 1e-4

dis: # Time-reversed Diffusion Sampler
  initial_scale: .1
  step_size: 1e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  initial_scale: .1
  step_size: 1e-3

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  initial_scale: 1.
  step_size: 1e-3

cmcd:  # General Schroedinger Bridge
  max_diffusion: 10.
  initial_scale: 1.
  step_size: 1e-3

scld:
  max_diffusion: 10.
  initial_scale: 1.
  step_size: 1e-3
  annealing_step_size: 1e-3
  n_sub_traj: 128

gsb:  # General Schroedinger Bridge
  max_diffusion: 10.
  initial_scale: .1
  step_size: 1e-3

all: # Parameters that are shared between all algorithms
  batch_size: 300

  # Settings related to conserving memory
  #memory_saver:
  #  buffer_on_cpu: True
  #  # "random" = choose 1 rng subtraj Or "cyclic"=cycle through subtraj or "all"=default subtraj
  #  subtraj_scheme: "cyclic" 
  #  accumulate_gradients: 1 # 1 means don't accumulate
