name: many_well_554
dim: 5
m: 5
delta: 4
has_entropy: False

fn:
  _target_: targets.many_well.ManyWell2
  dim: ${target.dim}
  m: ${target.m}
  delta: ${target.delta}
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 0.1
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 10.

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.01,0.001]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 1.

smc_rebuttal:
  initial_scale: 10.0
  target_ess: 0.99
  hmc_step_size: [0.2, 0.1]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 1.
  step_size: 1e-5

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 1
  step_size: 1e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 0.1
  step_size: 0.00001
  max_diffusion: 10.

dis: # DIS
  initial_scale: 0.1
  step_size: 0.00001
  max_diffusion: 10.

pis: # Path Integral Sampler
  step_size: 1e-5
  max_diffusion: 10.

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  initial_scale: 0.1
  step_size: 1e-3

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  initial_scale: 1.
  step_size: 1e-3

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 1. # sqrt(0.01 / (1 / 16))
  initial_scale: 1.
  step_size: 5e-4

scld:
  max_diffusion: 10. # sqrt(0.01 / (1 / 16))
  initial_scale: 1.
  step_size: 1e-4
  annealing_step_size: 1e-2
  n_sub_traj: 4

all: # Parameters that are shared between all algorithms
  batch_size: 2000
